### ISSUE TITLE
BIDS Helper plugin constructor failed on TriStatePerspectivesPlugin

### ISSUE THREAD

**Issue by MungBurger** [BIDeveloperExtensions/bideveloperextensions#103]
**Describe the bug**
Error Raised when Selecting Unused Columns report
Reference to directory C:\projects\BIDS Helper\GitHub\

**Version**
BIDS Helper encountered an error when Visual Studio started:
BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on TriStatePerspectivesPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 318

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 318
Inner exception:
Method not found: 'Void Microsoft.AnalysisServices.Design.Scripts..ctor(Microsoft.AnalysisServices.Cube)'.
   at BIDSHelper.BIDSHelperWindowActivatedPluginBase.OnEnable() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\Core\BIDSHelperWindowActivatedPluginBase.cs:line 112
   at BIDSHelper.Core.BIDSHelperPluginBase..ctor(BIDSHelperPackage package) in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\Core\BIDSHelperPluginBase.cs:line 47
   at BIDSHelper.TriStatePerspectivesPlugin..ctor(BIDSHelperPackage package) in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\SSAS\TriStatePerspectivesPlugin.cs:line 40

**To Reproduce**
In VS2019 - Right Click the bim file, Select unused columns report.

**Expected behavior**
The report would render

**Screenshots**
Error Raised

![ErrorMsg](https://user-images.githubusercontent.com/7283445/89134245-e8f56c00-d566-11ea-9a93-5bdc6e947b2a.png)

BIDS Version Screen Shot
![BIDs Error ](https://user-images.githubusercontent.com/7283445/89134344-c2840080-d567-11ea-820d-2fcca2ca5d0f.png)

Tool versions
![BI Dev Ext](https://user-images.githubusercontent.com/7283445/89134244-e7c43f00-d566-11ea-8bd7-908f70b68b49.png)

![SSDT_Ver](https://user-images.githubusercontent.com/7283445/89134246-e8f56c00-d566-11ea-9399-2a3a5610d078.png)

**Additional context**
After dumping the version info it appears that the problem is not specific to Unused Columns.

**Comment by furmangg** [comment]
We just released BI Developer Extensions v2.3.9 which should fix compatibility issues. Please try that (or wait for it to auto-update) and let me know.
