### ISSUE TITLE
VS 2017 + BI Dev Ext 2.3.9, can't deploy SSIS pacakges

### ISSUE THREAD

**Issue by coremancov** [BIDeveloperExtensions/bideveloperextensions#109]
**Describe the bug**
I just noticed I no longer have option to deploy a SSIS package from VS 2017 w/ SSDT 15.9.x & BI Dev Extensions 2.3.x.
Yes, the project is in Package deployment mode. 
![BiDevExt](https://user-images.githubusercontent.com/64172087/90833374-bd130e00-e2fc-11ea-96ee-d6e01095df0d.png)

**Version**
Take a screenshot of the Tools... Options... BIDS Helper... Version screen and post it here.
<see attached>

**To Reproduce**
BIDS Helper encountered an error when Visual Studio started:
BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on TriStatePerspectivesPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 318

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 318
Inner exception:
Method not found: 'Void Microsoft.AnalysisServices.Design.Scripts..ctor(Microsoft.AnalysisServices.Cube)'.
   at BIDSHelper.BIDSHelperWindowActivatedPluginBase.OnEnable() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\Core\BIDSHelperWindowActivatedPluginBase.cs:line 112
   at BIDSHelper.Core.BIDSHelperPluginBase..ctor(BIDSHelperPackage package) in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\Core\BIDSHelperPluginBase.cs:line 47
   at BIDSHelper.TriStatePerspectivesPlugin..ctor(BIDSHelperPackage package) in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\SSAS\TriStatePerspectivesPlugin.cs:line 40

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by furmangg** [comment]
Go to Tools... Extensions and Updates... and install any updates it prompts you for as your SSDT extension versions seem a bit behind. Let us know if that clears it up.

**Comment by coremancov** [comment]
I have updated the ssas extension after updating to SSDT 15.9.3 and BIDX 2.3.9
![BiDevExt](https://user-images.githubusercontent.com/64172087/90837841-0583f900-e308-11ea-9623-eac8553c56ac.png)
 , still no SSIS deployment options on SSIS project

**Comment by coremancov** [comment]
...and here's a current SSIS Project properties window.
![BiDevExt_SsisProjProps](https://user-images.githubusercontent.com/64172087/90837997-7d522380-e308-11ea-8257-9122b6769d25.png)
It's not a critical part of my work day, but when I do work on SSIS packages, I really prefer pushing SSIS packages from VS instead of other ways.

**Comment by furmangg** [comment]
We released BI Developer Extensions 2.4.0. This should specifically fix your issue.

**Comment by coremancov** [comment]
@furmangg - Thank you! Yes, that did it. I have the "Deploy (BIDS Helper)" properties now.
