### ISSUE TITLE
SSIS deploy unavailable in VS 16.7.2

### ISSUE THREAD

**Issue by jbaynhamuk** [BIDeveloperExtensions/bideveloperextensions#113]
Since upgrading VS19 to 16.7.2, I am now unable to see the BIDS Helper deploy configuration options in the project properties screen or deploy packages as before.

BIDS version is 2.4.0, and it appears in the About page. The Deploy SSIS option is set to True.

SSDT version is 16.0.62008.03130.

In the version node of the BIDS options I see this error:

BIDS Helper encountered an error when Visual Studio started:
BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on TriStatePerspectivesPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 341

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 341
Inner exception:
Method not found: 'Void Microsoft.AnalysisServices.Design.Scripts..ctor(Microsoft.AnalysisServices.Cube)'.
   at BIDSHelper.BIDSHelperWindowActivatedPluginBase.OnEnable() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\Core\BIDSHelperWindowActivatedPluginBase.cs:line 112
   at BIDSHelper.Core.BIDSHelperPluginBase..ctor(BIDSHelperPackage package) in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\Core\BIDSHelperPluginBase.cs:line 47
   at BIDSHelper.TriStatePerspectivesPlugin..ctor(BIDSHelperPackage package) in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\SSAS\TriStatePerspectivesPlugin.cs:line 40

I have tried an uninstall/reinstall cycle.

Thanks, J

**Comment by dgosbell** [comment]
Check the versions in the help about page with the supported versions in the table at the bottom of the [downloads page](https://bideveloperextensions.github.io/downloads/) it's possible that some of your components are not up to date.

**Comment by jbaynhamuk** [comment]
All looks OK to me, SSAS 2.9.13, SSRS 2.6.7, SSIS 3.9

Thanks for the quick reply!

**Comment by jbaynhamuk** [comment]
Anything else I can try/check?

**Comment by furmangg** [comment]
We've published an [updated release](https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.4.1) of BI Developer Extensions for Visual Studio 2019 that resolves this issue. Please note the compatible SSAS/SSIS/SSRS extension version.
