### ISSUE TITLE
Unable to cast object of type error

### ISSUE THREAD

**Issue by LeoG71** [BIDeveloperExtensions/bideveloperextensions#122]
On the 1st time when opening solution with SSIS package opened I get this error. I think because of that I can't open BIDS expression editor. 

```
Unable to cast object of type 'Microsoft.DataTransformationServices.Design.DtsPackageView' to type 'Microsoft.DataWarehouse.Design.EditorWindow'.
   at BIDSHelper.SSIS.ParametersWindowPlugin.OnWindowActivated(Window GotFocus, Window LostFocus) 
   in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\SSIS\ParametersWindowPlugin.cs:line 81

```
![image](https://user-images.githubusercontent.com/8144582/112905737-8a11d380-90b0-11eb-941e-77c1198359af.png)

```
BIDS Helper encountered an error when Visual Studio started:
BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on TriStatePerspectivesPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 341

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 341
Inner exception:
Method not found: 'Void Microsoft.AnalysisServices.Design.Scripts..ctor(Microsoft.AnalysisServices.Cube)'.
   at BIDSHelper.BIDSHelperWindowActivatedPluginBase.OnEnable() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\Core\BIDSHelperWindowActivatedPluginBase.cs:line 112
   at BIDSHelper.Core.BIDSHelperPluginBase..ctor(BIDSHelperPackage package) in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\Core\BIDSHelperPluginBase.cs:line 47
   at BIDSHelper.TriStatePerspectivesPlugin..ctor(BIDSHelperPackage package) in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\SSAS\TriStatePerspectivesPlugin.cs:line 40
```

![image](https://user-images.githubusercontent.com/8144582/112905828-b9284500-90b0-11eb-99b1-7949c42fbe53.png)

Here is the System info
```
Microsoft SQL Server Data Tools for Visual Studio 2017  (SSDT)
Version 15.9.28
VisualStudio.15.Release/15.9.28+28307.1274
Microsoft .NET Framework
Version 4.8.04084

Installed Version: IDE Standard

Microsoft Visual Studio Tools for Applications 2017   00371-40000-00001-AA864
Microsoft Visual Studio Tools for Applications 2017

AnkhSVN - Subversion Support for Visual Studio   2.7.12815.35086
AnkhSVN - Subversion Support for Visual Studio 2.7.12815.35086 
 * Ankh.Package 2.7.12815.35086
 * Subversion 1.9.5 via SharpSvn 1.9005.3940.224
 * Git/LibGit2 0.24.0 via SharpGit 0.2401.1116.230

SharpSvn is linked to: Apr 1.5.2, Apr-util 1.5.4, Cyrus Sasl 2.1.26, eXpat 2.2.0, LibSSH2 1.8.0, OpenSSL 1.0.2k  26 Jan 2017, Serf 1.3.9, SQLite 3.17.0, Subversion 1.9.5-SharpSvn, Utf8proc 1.1.5, ZLib 1.2.8
SharpSvn is optionally linked to: Berkeley DB 4.4.20, SharpPlink 0.67.0(SharpSvn)

SharpGit is linked to: Apr 1.5.1, Apr-Util 1.5.4, eXpat 2.1.0, Libgit2 0.24.0, LibSSH2 1.7.0, OpenSSL 1.0.2h  3 May 2016, Subversion 1.9.3, Utf8proc 1.1.5, ZLib 1.2.8

ApexSQL Complete   1.0
ApexSQL Complete Visual Studio Addin Component

ApexSQL Refactor   1.0
ApexSQL Refactor Visual Studio Addin Component

ApexSQL Stub   1.0


BI Developer Extensions for Visual Studio 2017   2.4.0
BI Developer Extensions v2.4.0 for Visual Studio 2017 - An add-in to extend SQL Server Data Tools

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

ConfigureCompareFilesCommand Extension   1.0
ConfigureCompareFilesCommand Visual Studio Extension Detailed Info

COZYROC SSIS+   1.9.1049
Additional features for SSIS solutions

For more information about COZYROC SSIS+, see the  website at
http://www.cozyroc.com
For customer support, call 1-919-249-7421.
Copyright (c) 2006-2019 COZYROC LLC

Customize Visual Studio Window Title   4.0
This lightweight extension allows changing the window title of Visual Studio to include a folder tree with a configurable min depth and max depth distance from the solution/project file, and the use of special tags to help with many other possible scenarios (Git, Hg, TFS, SVN...). 
Solution-specific overriding rules are available as well to cover virtually any possible renaming needs. It can also be configured so that the rules apply only when at least two instances of Visual Studio are running with the same window title.
This is particularly useful when branching a solution/project: it becomes possible to easily identify which branch you are working on, in case both would have the same solution/project name.

Devart Template Editor   1.0.11.0
Editor for T4 and Devart template files with syntax coloring and IntelliSense.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open in Notepad++   1.1.12
Adds a menu command that lets you open any solution, project, folder and file in Notepad++

Project   1.0
Information about my package

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Analysis Services   15.0.19356.0
Microsoft SQL Server Analysis Services Designer 
Version 15.0.19356.0

SQL Server Data Tools   15.1.62002.01090
Microsoft SQL Server Data Tools

SQL Server Integration Services   15.0.2000.93
Microsoft SQL Server Integration Services Designer
Version 15.0.2000.93

SQL Server Reporting Services   15.0.19124.0
Microsoft SQL Server Reporting Services Designers 
Version 15.0.19124.0

SsmsVsIntegration   1.0
Information about my package

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
https://GitHub.com/EWSoftware/VSSpellChecker
```

Let me know if you need more information. 
Thanks

**Comment by furmangg** [comment]
We've published an [updated release](https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.4.1) of BI Developer Extensions for Visual Studio 2019 that resolves this issue. Please note the compatible SSIS extension version.
