### ISSUE TITLE
Dimension Data Type Discrepancy Check Context Menu Missing

### ISSUE THREAD

**Issue by rmegal** [BIDeveloperExtensions/bideveloperextensions#126]
Just installed VS2019 Community 16.10.0, the SSAS extension, and this extension. The "Dimension Data Type Discrepancy Check" menu is not showing up.

I restarted VS2019. No joy.

What am I missing?

**Comment by furmangg** [comment]
Thanks for reporting. Can you take a screenshot of the Tools... Options... BIDS Helper... Version screen and post it here.

**Comment by rmegal** [comment]
Here is the error:
```
BIDS Helper encountered an error when Visual Studio started:
BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on TriStatePerspectivesPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 341

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 341
Inner exception:
Method not found: 'Void Microsoft.AnalysisServices.Design.Scripts..ctor(Microsoft.AnalysisServices.Cube)'.
   at BIDSHelper.BIDSHelperWindowActivatedPluginBase.OnEnable() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\Core\BIDSHelperWindowActivatedPluginBase.cs:line 112
   at BIDSHelper.Core.BIDSHelperPluginBase..ctor(BIDSHelperPackage package) in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\Core\BIDSHelperPluginBase.cs:line 47
   at BIDSHelper.TriStatePerspectivesPlugin..ctor(BIDSHelperPackage package) in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\SSAS\TriStatePerspectivesPlugin.cs:line 40

```
![BIDS_Helper_20210607](https://user-images.githubusercontent.com/213904/121010260-e63c4800-c730-11eb-9f18-35bb0f052e6c.gif)

**Comment by rmegal** [comment]
I tried updating to VS2019 16.10.1, and then downgrading to 16.9.7. The error still exists:
```
BIDS Helper encountered an error when Visual Studio started:
BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on TriStatePerspectivesPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 341

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 341
Inner exception:
Method not found: 'Void Microsoft.AnalysisServices.Design.Scripts..ctor(Microsoft.AnalysisServices.Cube)'.
   at BIDSHelper.BIDSHelperWindowActivatedPluginBase.OnEnable() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\Core\BIDSHelperWindowActivatedPluginBase.cs:line 112
   at BIDSHelper.Core.BIDSHelperPluginBase..ctor(BIDSHelperPackage package) in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\Core\BIDSHelperPluginBase.cs:line 47
   at BIDSHelper.TriStatePerspectivesPlugin..ctor(BIDSHelperPackage package) in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\SSAS\TriStatePerspectivesPlugin.cs:line 40
```
![image](https://user-images.githubusercontent.com/213904/122047339-a6ff9e00-cda5-11eb-82b9-2ff33813987a.png)

**Comment by AgentRatty** [comment]
I echo this bug. I am using VS Community 2019 Version 16.10.3 (.Net framework 4.7.03190) and I am not seeing the Data Type Discrepancy context menu when looking at dimensions. This is a key feature I use all the time. I am also not getting an error as per OP.

Thanks in advance for your help on this.
--AR

Microsoft Visual Studio Community 2019
Version 16.10.3
VisualStudio.16.Release/16.10.3+31424.327
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Community

Microsoft Visual Studio Tools for Applications 2019   00435-60000-00000-AA957
Microsoft Visual Studio Tools for Applications 2019

Azure App Service Tools v3.0.0   16.10.526.50910
Azure App Service Tools v3.0.0

BI Developer Extensions for Visual Studio 2019   2.4.0
BI Developer Extensions v2.4.0 for Visual Studio 2019 - An add-in to extend SQL Server Data Tools

C# Tools   3.10.0-4.21318.11+7ceb633154acb9d716fd3eb2b6df1a0468d8e416
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

NuGet Package Manager   5.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Project   1.0
Information about my package

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Redgate SQL Search   3.5.5.2703
Search functionality for SQL Server databases, from within Visual Studio

SQL Server Analysis Services   15.0.19526.0
Microsoft SQL Server Analysis Services Designer 
Version 15.0.19526.0

SQL Server Data Tools   16.0.62106.24090
Microsoft SQL Server Data Tools

SQL Server Integration Services   15.0.2000.167
Microsoft SQL Server Integration Services Designer
Version 15.0.2000.167

SQL Server Reporting Services   15.0.19528.0
Microsoft SQL Server Reporting Services Designers 
Version 15.0.19528.0

SsmsVsIntegration   1.0
Information about my package

Visual Basic Tools   3.10.0-4.21318.11+7ceb633154acb9d716fd3eb2b6df1a0468d8e416
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

**Comment by furmangg** [comment]
We've published an [updated release](https://github.com/BIDeveloperExtensions/bideveloperextensions/releases/tag/v2.4.1) of BI Developer Extensions for Visual Studio 2019 that resolves this issue. Please note the compatible SSAS extension version.
