### ISSUE TITLE
BIDS Helper encountered an error when Visual Studio started

### ISSUE THREAD

**Issue by sebtpl27** [BIDeveloperExtensions/bideveloperextensions#141]
**Describe the bug**
Just noticed that no BIDHelper features seem to be available in VS.  (SSIS development).
Looking at Tools/Options/BI Developer Extensions/Version, I get "encountered an error when VS started):

BIDS Helper encountered an error when Visual Studio started:
BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on DeployPackagesPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 341

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 341
Inner exception:
Could not load file or assembly 'Microsoft.DataWarehouse.VsIntegration, Version=16.2.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SSIS.DeployPackagesPlugin.RegisterClassesForCOM()
   at BIDSHelper.SSIS.DeployPackagesPlugin..ctor(BIDSHelperPackage package) in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\SSIS\DeployPackagesPlugin.cs:line 32BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on ExpressionHighlighterPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 341

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 341
Inner exception:
Could not load file or assembly 'Microsoft.AnalysisServices.Controls, Version=16.2.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SSIS.ExpressionHighlighterPlugin..ctor(BIDSHelperPackage package)BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on ExpressionListPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 341

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 341
Inner exception:
Could not load file or assembly 'Microsoft.DataWarehouse, Version=16.2.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.BIDSHelperWindowActivatedPluginBase.OnEnable() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\Core\BIDSHelperWindowActivatedPluginBase.cs:line 112
   at BIDSHelper.SSIS.ExpressionListPlugin.OnEnable() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\SSIS\ExpressionListPlugin.cs:line 53
   at BIDSHelper.Core.BIDSHelperPluginBase..ctor(BIDSHelperPackage package) in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\Core\BIDSHelperPluginBase.cs:line 47
   at BIDSHelper.SSIS.ExpressionListPlugin..ctor(BIDSHelperPackage package) in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\SSIS\ExpressionListPlugin.cs:line 28BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on ParametersWindowPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 341

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 341
Inner exception:
Could not load file or assembly 'Microsoft.DataWarehouse, Version=16.2.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.BIDSHelperWindowActivatedPluginBase.OnEnable() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\Core\BIDSHelperWindowActivatedPluginBase.cs:line 112
   at BIDSHelper.Core.BIDSHelperPluginBase..ctor(BIDSHelperPackage package) in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\Core\BIDSHelperPluginBase.cs:line 47
   at BIDSHelper.SSIS.ParametersWindowPlugin..ctor(BIDSHelperPackage package) in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\SSIS\ParametersWindowPlugin.cs:line 29BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on VariablesWindowPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 341

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\BidsHelperPackage.cs:line 341
Inner exception:
Could not load file or assembly 'Microsoft.DataTransformationServices.Controls, Version=16.100.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.BIDSHelperWindowActivatedPluginBase.OnEnable() in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\Core\BIDSHelperWindowActivatedPluginBase.cs:line 112
   at BIDSHelper.Core.BIDSHelperPluginBase..ctor(BIDSHelperPackage package) in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\Core\BIDSHelperPluginBase.cs:line 47
   at BIDSHelper.SSIS.VariablesWindowPlugin..ctor(BIDSHelperPackage package) in C:\projects\BIDS Helper\GitHub\bideveloperextensions2\SSIS\VariablesWindowPlugin.cs:line 53

**Version**
![image](https://user-images.githubusercontent.com/128051229/225618951-792ef9c5-23ba-467b-879c-1a805239f880.png)

**To Reproduce**
No particular action, it's just my particular setup.
But, for example, the SSIS Variables extensions are no longer visible.

**Expected behavior**
BIDS Helper works.

**Screenshots**
VS version window:
![image](https://user-images.githubusercontent.com/128051229/225619222-ffc0d920-f1a9-4b0b-8b9d-6ca4c0e6b71b.png)
SSIS Projects version:
![image](https://user-images.githubusercontent.com/128051229/225619383-eaaf8b0f-265b-4666-b449-e54d9f8791e4.png)

**Additional context**
I know my version of SSIS Projects extension is out of date.  I can't upgrade it, because we have a massive codebase using some awful, crappy Oracle driver which won't work properly with newer versions.  However, BI Dev Extensions has been working fine with this setup for months.
Tried uninstalling and reinstalling BI Dev extensions, but that didn't fix it.

**Comment by sebtpl27** [comment]
I don't know what DeployPackagesPlugin is: but if there's some way of disabling that so that I can go on using everything else in BIDevExtensions, happy to do that.

**Comment by furmangg** [comment]
Luckily I think I can help you. I believe what you are saying is that BI Developer Extensions 2.4.0 (the previous release) was working fine with SSIS 3.16. Go to the [downloads page](https://bideveloperextensions.github.io/downloads/) and click the link for the VS2019 version of BI Developer Extensions 2.4.0 and download it. The file you're looking for is BI.Developer.Extensions.2.4.0.for.VS2019.vsix.

In Visual Studio 2019, uninstall the BI Developer Extensions 2.4.1 release from Extensions... Manage Extensions... Installed. Then install the BI.Developer.Extensions.2.4.0.for.VS2019.vsix file you downloaded. Open Visual Studio 2019 and open the Extensions... Manage Extensions... Installed UI. Click on BI Developer Extensions and uncheck "Automatically update this extension" so that it won't auto-update to 2.4.1.

I'm going to close this issue in anticipation this fixed it, but please write back if it didn't.

For anyone else seeing this issue in the future, I have copies of historical BI Developer Extensions releases and if you don't see it linked to that specific version on the downloads page or the releases page, let me know and I can add it.

**Comment by sebtpl27** [comment]
Perfect!  Regressing to 2.4.0 has fixed it.  It must have auto-updated to 2.4.1: so I've got the extension disabled for auto-update now.  Thank you!
