### ISSUE TITLE
Cannot Install - Options Window Error

### ISSUE THREAD

**Issue by paulhocker** [BIDeveloperExtensions/bideveloperextensions#21]
**Summary**
The package installs without any errors. After restarting, the package is not available, and the options windows has errors.

**System Information**

Microsoft Visual Studio Professional 2015
Version 14.0.25420.01 Update 3
Microsoft .NET Framework
Version 4.7.02053

Installed Version: Professional

LightSwitch for Visual Studio 2015   00325-60004-60233-AA429
Microsoft LightSwitch for Visual Studio 2015

Visual Basic 2015   00325-60004-60233-AA429
Microsoft Visual Basic 2015

Visual C# 2015   00325-60004-60233-AA429
Microsoft Visual C# 2015

Visual C++ 2015   00325-60004-60233-AA429
Microsoft Visual C++ 2015

Visual F# 2015   00325-60004-60233-AA429
Microsoft Visual F# 2015

Windows Phone SDK 8.0 - ENU   00325-60004-60233-AA429
Windows Phone SDK 8.0 - ENU

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11107.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

BI Developer Extensions for Visual Studio 2015   2.1.1
BI Developer Extensions v2.1.1 for Visual Studio 2015 - An add-in to extend SQL Server Data Tools

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2015 ENU   14.0.23025
Microsoft Office Developer Tools for Visual Studio 2015 ENU

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

Telerik ASP.NET AJAX VSExtensions   2017.3.906.0
Progress® Telerik® UI for ASP.NET AJAX Visual Studio extensions

Telerik ASP.NET Core VSExtensions   2017.3.1017.0
Progress® Telerik® UI for ASP.NET Core Visual Studio extensions

Telerik ASP.NET MVC VSExtensions   2017.3.1017.0
Progress® Telerik® UI for ASP.NET MVC Visual Studio extensions

Telerik Reporting   
For more information please visit http://www.telerik.com/reporting. Copyright © 2005–2018 Telerik AD

TypeScript   1.8.34.0
TypeScript tools for Visual Studio

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

**Here is the error message**

BIDS Helper encountered an error when Visual Studio started:
Could not load file or assembly 'Microsoft.DataWarehouse' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at BIDSHelper.Core.VersionInfo.get_SqlServerVersion() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\Core\VersionInfo.cs:line 94
   at BIDSHelper.BIDSHelperPackage.SwitchVsixManifest() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 244
   at BIDSHelper.BIDSHelperPackage.Initialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 109

**Comment by furmangg** [comment]
You don't have the SSAS/SSIS/SSRS part of SSDT installed:
https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt
