### ISSUE TITLE
Usage based optimization failing

### ISSUE THREAD

**Issue by Gradomyr** [BIDeveloperExtensions/bideveloperextensions#35]
I used to have an older version of BIDS Helper. Then I updated my Visual studio to version 2017 (15.5.6). In this new VS my Usage Based Optimization is not working for multidimensional cube. See the detailed error below. I found online that it must be because of missing BIDS file. So I have installed the latest version of BI Developer Extensions (2.1.1) from GitHub. I've got some other functions working. Like, for example, Edit Aggregations or Update All Estimated Counts. But the Aggregations tab remained unchanged. I don't get the additional toolbar buttons. And Usage Based Optimization keeps giving the same error. I do have additional toolbar buttons on other tabs of Cube Design window.

===================================

The system cannot locate the object specified.
 (Microsoft Visual Studio)

------------------------------
Program Location:

   at EnvDTE.IVsExtensibility.RunWizardFile(String bstrWizFilename, Int32 hwndOwner, Object[]& vContextParams)
   at Microsoft.DataWarehouse.VsIntegration.Shell.Project.FileProjectHierarchy.RunAddNewItemWizard(String pszItemName, Int32 cFilesToOpen, String[] rgpszFilesToOpen, IntPtr hwndDlg)
   at Microsoft.DataWarehouse.VsIntegration.Shell.Project.FileProjectHierarchy.RunWizard(String wizardName, String newItemName)
   at Microsoft.DataWarehouse.DataWarehouseUtilities.RunWizard(String wizardName, IServiceProvider serviceProvider, Object[] stackParameters)
   at Microsoft.AnalysisServices.Design.AnalysisServicesUtilities.InvokeUsageBasedOptimizationWizard(MeasureGroup measureGroup, Partition[] selectedPartitions)
   at Microsoft.AnalysisServices.Design.Aggregations.AggregationsEditor.OnUBO(MenuCommand menuCommand, CommandHandlingArgs args)

**Comment by dgosbell** [comment]
That looks like you have an issue with the Microsoft Analysis Services designers add-in for Visual Studio. You might need to try re-installing or repairing that. But none of those function calls in the call stack you posted are coming from BI Developer Extensions as you would see references to BIDSHelper (the original project name) code if these errors were coming out of our add-in. 

You should be able to disable BI Developer Extensions and the Aggregation Wizard should still work. Can you try doing that to confirm that BI Developer Extensions is not a factor in this error?

**Comment by Gradomyr** [comment]
Yes, seems that something else is the issue. Sorry for disturbing you.
