### ISSUE TITLE
Error On Parameters Window In Package-Deployment Mode

### ISSUE THREAD

**Issue by BillBoroson** [BIDeveloperExtensions/bideveloperextensions#69]
**Describe the bug**
In package-deployment mode, I click on the 'Parameters' window and I get the below error message.  After dismissing the error message, clicking on the 'Add Parameter' button does nothing.  

===================================
Unable to cast object of type 'ParameterGridControl' to type 'Microsoft.SqlServer.Management.UI.Grid.DlgGridControl'. (Microsoft Visual Studio)
------------------------------
Program Location:

   at BIDSHelper.SSIS.ParametersWindowManager.SetupControl() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\SSIS\ParametersWindowPlugin.cs:line 202
   at BIDSHelper.SSIS.ParametersWindowManager.editorWindow_ActiveViewChanged(Object sender, EventArgs e) in C:\projects\BIDS Helper\GitHub\bideveloperextensions\SSIS\ParametersWindowPlugin.cs:line 165
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Microsoft.DataWarehouse.Design.EditorWindow.OnActiveViewChanged(EventArgs e)
   at Microsoft.DataTransformationServices.Design.DtsPackageView.OnActiveViewChanged(EventArgs args)

**Version**
![image](https://user-images.githubusercontent.com/18312540/58368403-a9d77f80-7eba-11e9-881f-10f2fa593a8b.png)

**To Reproduce**
1. Open a new SSIS project.  
2. Switch to package-deployment mode.
3. Click on 'Parameters' window.
4. See error.

**Expected behavior**
No error appears and users can add/edit/delete package parameters.

**Screenshots**

**Additional context**

**Comment by BillBoroson** [comment]
Since parameters are not supported in package-deployment mode, I guess this error isn't so bad.  Probably should be fixed but it's not urgent.  I'll close this issue.

**Comment by furmangg** [comment]
Thanks Bill. Yes. Known issue with another bug open. I have the fix complete but haven’t finished a complete retest on the latest SSDT. Hopefully will have the release out in a week or two.
