### ISSUE TITLE
BIDS Helper - Error: Sortable Package Properties Report

### ISSUE THREAD

**Issue by dbunch1962** [BIDeveloperExtensions/bideveloperextensions#89]
I get the following error when I try to run the **Sortable Package Properties Report** in Visual Studio 2019:

```
Unable to cast object of type 'Microsoft.DataTransformationServices.Project.DataTransformationsProjectManager' to type 'Microsoft.DataWarehouse.Project.DataWarehouseProjectManager'.
   at BIDSHelper.SSIS.SSISHelpers.GetTargetServerVersion(Project project) in C:\projects\BIDS Helper\GitHub\bideveloperextensions\SSIS\SSISHelpers.cs:line 102
   at BIDSHelper.SSAS.NonDefaultPropertiesPlugin.OrchestrateSSISProjectScan(Project p, UIHierarchyItem hierItem) in C:\projects\BIDS Helper\GitHub\bideveloperextensions\SSAS\NonDefaultPropertiesPlugin.cs:line 344
   at BIDSHelper.SSAS.NonDefaultPropertiesPlugin.Exec() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\SSAS\NonDefaultPropertiesPlugin.cs:line 193
```

**Version Info**
Microsoft Visual Studio Enterprise 2019 Version 16.3.10
VisualStudio.16.Release/16.3.10+29519.87
Microsoft .NET Framework Version 4.8.03752

BI Developer Extensions for Visual Studio 2019   2.3.4
BI Developer Extensions v2.3.4 for Visual Studio 2019 - An add-in to extend SQL Server Data Tools

**To Reproduce**
1. In VS Solution Explorer, right-click package.dtsx to bring-up context-menu
2. Click on Sortable Package Properties Report...
![image](https://user-images.githubusercontent.com/41155219/74543922-df6e3e00-4f0b-11ea-9311-416e5fc019bf.png)

3. BIDS Helper - Error window appears: 
![image](https://user-images.githubusercontent.com/41155219/74544004-0167c080-4f0c-11ea-8db2-11d4337c6889.png)

**Expected behavior**
BIDS Helper generates _Package Properties XLSX_ report.

**Additional Error Info**
![image](https://user-images.githubusercontent.com/41155219/74544367-9f5b8b00-4f0c-11ea-97c9-f055d4d096aa.png)

```
BIDS Helper encountered an error when Visual Studio started:
BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on TriStatePerspectivesPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 283

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 283
Inner exception:
Could not load file or assembly 'Microsoft.AnalysisServices.Controls.AS, Version=15.4.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.TriStatePerspectivesPlugin..ctor(BIDSHelperPackage package)
Inner exception:
Could not load file or assembly 'file:///C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\SSIS\150\BISHARED\Microsoft.AnalysisServices.Controls.AS.DLL' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SSAS.M2MMatrixCompressionPlugin..ctor(BIDSHelperPackage package)BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on CalcHelpersPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 283

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 283
Inner exception:
Could not load file or assembly 'file:///C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\SSIS\150\BISHARED\Microsoft.AnalysisServices.Controls.AS.DLL' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SSAS.M2MMatrixCompressionPlugin..ctor(BIDSHelperPackage package)BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on DeployPerspectivesPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 283

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 283
Inner exception:
Could not load file or assembly 'file:///C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\SSIS\150\BISHARED\Microsoft.AnalysisServices.Controls.AS.DLL' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SSAS.M2MMatrixCompressionPlugin..ctor(BIDSHelperPackage package)BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on EstimatedCountsPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 283

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 283
Inner exception:
Could not load file or assembly 'file:///C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\SSIS\150\BISHARED\Microsoft.AnalysisServices.Controls.AS.DLL' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SSAS.M2MMatrixCompressionPlugin..ctor(BIDSHelperPackage package)BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on M2MMatrixCompressionPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 283

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 283
Inner exception:
Could not load file or assembly 'file:///C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\SSIS\150\BISHARED\Microsoft.AnalysisServices.Controls.AS.DLL' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SSAS.M2MMatrixCompressionPlugin..ctor(BIDSHelperPackage package)
```

**Comment by ChrisSwe** [comment]
Related to #87 ?

**Comment by dbunch1962** [comment]
Yes - this is related to #87 
I was able to get VS 2019 to load BIDS Helper by creating a copy of assembly file _AnalysisServices.Controls.dll_ and renaming the copy to _AnalysisServices.Controls.**AS**.dll_

In folder:
_C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\SSIS\150\BIShared_

However, I still get the original error:
```
Unable to cast object of type 'Microsoft.DataTransformationServices.Project.DataTransformationsProjectManager' to type 'Microsoft.DataWarehouse.Project.DataWarehouseProjectManager'.
   at BIDSHelper.SSIS.SSISHelpers.GetTargetServerVersion(Project project) in C:\projects\BIDS Helper\GitHub\bideveloperextensions\SSIS\SSISHelpers.cs:line 102
   at BIDSHelper.SSIS.SortablePackagePropertiesPlugin.Exec() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\SSIS\SortablePackagePropertiesPlugin.cs:line 133
```
