### ISSUE TITLE
Tabular Display Folders Error

### ISSUE THREAD

**Issue by tperando** [BIDeveloperExtensions/bideveloperextensions#90]
**Describe the bug**
Tabular Display Folders is throwing an error message.
![image](https://user-images.githubusercontent.com/61719417/75735081-ac77c880-5cc7-11ea-80e5-100228bb11b3.png)

**Version**
About Visual Studio says that this is SSDT 2017 v. 15.9.2
![image](https://user-images.githubusercontent.com/61719417/75735863-b13d7c00-5cc9-11ea-91f0-5a92919116af.png)

Under Tools... Options... BIDS Helper...
it says that this is BI Developer Extensions for SQL Server 2019.  This was installed via Extensions and Updates.
![image](https://user-images.githubusercontent.com/61719417/75735536-e4cbd680-5cc8-11ea-978b-75e962a24ba8.png)
Also while under this menu i receive the following error message...

BIDS Helper encountered an error when Visual Studio started:
BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on TriStatePerspectivesPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 283

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 283
Inner exception:
Could not load file or assembly 'Microsoft.AnalysisServices.Controls.AS, Version=15.4.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.TriStatePerspectivesPlugin..ctor(BIDSHelperPackage package)
Inner exception:
Could not load file or assembly 'file:///C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\SQL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\SSIS\150\BISHARED\Microsoft.AnalysisServices.Controls.AS.DLL' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SSAS.M2MMatrixCompressionPlugin..ctor(BIDSHelperPackage package)BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on CalcHelpersPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 283

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 283
Inner exception:
Could not load file or assembly 'file:///C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\SQL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\SSIS\150\BISHARED\Microsoft.AnalysisServices.Controls.AS.DLL' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SSAS.M2MMatrixCompressionPlugin..ctor(BIDSHelperPackage package)BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on DeployPerspectivesPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 283

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 283
Inner exception:
Could not load file or assembly 'file:///C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\SQL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\SSIS\150\BISHARED\Microsoft.AnalysisServices.Controls.AS.DLL' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SSAS.M2MMatrixCompressionPlugin..ctor(BIDSHelperPackage package)BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on EstimatedCountsPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 283

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 283
Inner exception:
Could not load file or assembly 'file:///C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\SQL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\SSIS\150\BISHARED\Microsoft.AnalysisServices.Controls.AS.DLL' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SSAS.M2MMatrixCompressionPlugin..ctor(BIDSHelperPackage package)BIDS Helper encountered an error when Visual Studio started:
BIDS Helper plugin constructor failed on M2MMatrixCompressionPlugin: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 283

Inner exception:
Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BIDSHelper.BIDSHelperPackage.OriginalInitialize() in C:\projects\BIDS Helper\GitHub\bideveloperextensions\BidsHelperPackage.cs:line 283
Inner exception:
Could not load file or assembly 'file:///C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\SQL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\SSIS\150\BISHARED\Microsoft.AnalysisServices.Controls.AS.DLL' or one of its dependencies. The system cannot find the file specified.
   at BIDSHelper.SSAS.M2MMatrixCompressionPlugin..ctor(BIDSHelperPackage package)

**To Reproduce**
1. Open SSAS project in 'SQL Server 2014 / SQL Server 2012 SP1 (1103)' Compatibility Level.
2. Right click on Model.bim
3. Click on "Tabular Display Folders..."

**Expected behavior**
Expecting to see the BIDS Helper Tabular Display Folder GUI.
![image](https://user-images.githubusercontent.com/61719417/75735939-e649ce80-5cc9-11ea-8d7f-1015cce58c37.png)

**Comment by furmangg** [comment]
We just released v2.3.5 of BI Developer Extensions which resolves the problem. Please go to the manage Extensions window and ensure you install the update to BI Developer Extensions (and the other SSDT extensions, too). Thanks for your patience. Please let us know if this doesn't resolve your issue.
